name: Sales Intel Automation

on:
  schedule:
    - cron: '0 6 * * *'
  push:
    branches: [master]
  release:
    types: [created] 

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Test with Maven
        run: |
          mvn clean install test
          
      - name: Execution Results Upload Artifact For Cucumber Reporting
        uses: actions/upload-artifact@v3
        with: 
              name: Cucumber Report Latest Results
              path: src/test/resources/Reports/CucumberReports/cucumber-html-reports/
          
      - name: Execution Results Download Artifact  For Cucumber Reporting     
        uses: actions/download-artifact@v3
        with:
          name: Cucumber Report Latest Results
          
      - name: Execution Results Upload Artifact For Extent Report
        uses: actions/upload-artifact@v3
        with: 
              name: Extent Report Latest Results
              path: test-output/spark/              

      - name: Execution Results Download Artifact For Extent Report      
        uses: actions/download-artifact@v3
        with:
          name: Extent Report Latest Results
          
      - name: Execution Results Download Artifact File List
        run: ls -R
        
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          connection_url: ${{secrets.MAIL_CONNECTION}}
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Github Actions Automation Result
          to: pssraja94@gmail.com
          from: pssraja94@gmail.com
          html_body: "Hi Team,\nBuild job of ${{github.repository}} completed successfully!\nPlease find the Attachment\nThanks\nMuthukumar"
          ignore_cert: true
          convert_markdown: true
          attachments: attachments.zip,git.diff,./dist/static/*.js
          priority: high
        

        
